"""add started tracking to user_progress

Revision ID: 1ff8d23268ec
Revises: abad24c8929b
Create Date: 2026-01-28 20:22:05.181974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1ff8d23268ec'
down_revision: Union[str, Sequence[str], None] = 'abad24c8929b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_progress', sa.Column('started', sa.Boolean(), nullable=False))
    op.add_column('user_progress', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('uq_user_task'), table_name='user_progress')
    op.create_index(op.f('ix_user_progress_id'), 'user_progress', ['id'], unique=False)
    op.create_unique_constraint('uq_user_task_progress', 'user_progress', ['user_id', 'task_id'])
    op.drop_column('user_progress', 'updated_at')
    op.drop_column('user_progress', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_progress', sa.Column('status', mysql.ENUM('not_started', 'in_progress', 'done'), nullable=True))
    op.add_column('user_progress', sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True))
    op.drop_constraint('uq_user_task_progress', 'user_progress', type_='unique')
    op.drop_index(op.f('ix_user_progress_id'), table_name='user_progress')
    op.create_index(op.f('uq_user_task'), 'user_progress', ['user_id', 'task_id'], unique=True)
    op.drop_column('user_progress', 'started_at')
    op.drop_column('user_progress', 'started')
    # ### end Alembic commands ###
