"""add roadmaps table

Revision ID: 80c8491539cd
Revises: 4edde5ce6f0f
Create Date: 2026-01-27 00:07:32.822778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80c8491539cd'
down_revision: Union[str, Sequence[str], None] = '4edde5ce6f0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roadmaps', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('roadmaps', sa.Column('difficulty', sa.String(length=50), nullable=False))
    op.add_column('roadmaps', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_roadmaps_id'), 'roadmaps', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roadmaps_id'), table_name='roadmaps')
    op.drop_column('roadmaps', 'created_at')
    op.drop_column('roadmaps', 'difficulty')
    op.drop_column('roadmaps', 'description')
    # ### end Alembic commands ###
