"""add user_progress table

Revision ID: abad24c8929b
Revises: 4828682e5073
Create Date: 2026-01-27 00:46:44.777097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'abad24c8929b'
down_revision: Union[str, Sequence[str], None] = '4828682e5073'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_progress', sa.Column('completed', sa.Boolean(), nullable=False))
    op.add_column('user_progress', sa.Column('score', sa.Integer(), nullable=True))
    op.add_column('user_progress', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_progress', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('uq_user_task'), table_name='user_progress')
    op.create_index(op.f('ix_user_progress_id'), 'user_progress', ['id'], unique=False)
    op.create_unique_constraint('uq_user_task_progress', 'user_progress', ['user_id', 'task_id'])
    op.drop_column('user_progress', 'updated_at')
    op.drop_column('user_progress', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_progress', sa.Column('status', mysql.ENUM('not_started', 'in_progress', 'done'), nullable=True))
    op.add_column('user_progress', sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True))
    op.drop_constraint('uq_user_task_progress', 'user_progress', type_='unique')
    op.drop_index(op.f('ix_user_progress_id'), table_name='user_progress')
    op.create_index(op.f('uq_user_task'), 'user_progress', ['user_id', 'task_id'], unique=True)
    op.drop_column('user_progress', 'created_at')
    op.drop_column('user_progress', 'completed_at')
    op.drop_column('user_progress', 'score')
    op.drop_column('user_progress', 'completed')
    # ### end Alembic commands ###
